# Generated by Django 4.0.6 on 2022-07-31 04:50

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.SmallIntegerField()),
                ('eyeColor', models.CharField(max_length=20)),
                ('balance', models.CharField(max_length=50)),
                ('tags', djongo.models.fields.JSONField()),
                ('friends', djongo.models.fields.JSONField()),
                ('greeting', models.CharField(max_length=100)),
                ('favoriteFruit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=255)),
                ('post_description', models.TextField()),
                ('comment', djongo.models.fields.JSONField()),
                ('tags', djongo.models.fields.JSONField()),
                ('user_detail', djongo.models.fields.JSONField()),
            ],
        ),
    ]
